// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmKjvEHcOZNcv39bCcecDej3nxGP4ISY',
    appId: '1:761346352606:web:d18d2f85267db09866e94f',
    messagingSenderId: '761346352606',
    projectId: 'flutterballoon',
    authDomain: 'flutterballoon.firebaseapp.com',
    storageBucket: 'flutterballoon.appspot.com',
    measurementId: 'G-C6DXBT4FVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBslYVNqPve2cLzycl36jIu8Sjsa-3dfRk',
    appId: '1:761346352606:android:dcd8094adfb2c47766e94f',
    messagingSenderId: '761346352606',
    projectId: 'flutterballoon',
    storageBucket: 'flutterballoon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEW_DIPoYFMiB7UMb4btcLPy2Kfcn6XHc',
    appId: '1:761346352606:ios:bda561cf8df0ce5866e94f',
    messagingSenderId: '761346352606',
    projectId: 'flutterballoon',
    storageBucket: 'flutterballoon.appspot.com',
    iosClientId:
        '761346352606-ni3iiirtitpb7jbf7qaojjlm9om0qk3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdbChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEW_DIPoYFMiB7UMb4btcLPy2Kfcn6XHc',
    appId: '1:761346352606:ios:bda561cf8df0ce5866e94f',
    messagingSenderId: '761346352606',
    projectId: 'flutterballoon',
    storageBucket: 'flutterballoon.appspot.com',
    iosClientId:
        '761346352606-ni3iiirtitpb7jbf7qaojjlm9om0qk3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bdbChallenge',
  );
}
